behaviors:
  CrawlerDiverse:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 1000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 32.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 20.0
      mede: False
      mede_dropout: 0.5
      mede_continuous: False
      mede_init_divcoef: 1.0
      mede_target_divcoef: 1.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: none
      n_modes: 4
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 1000
    summary_freq: 1000
