behaviors:
  VisualHallway:
    trainer: sac
    batch_size: 64
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 1.0e7
    memory_size: 128
    normalize: false
    steps_per_update: 10
    num_layers: 1
    time_horizon: 64
    sequence_length: 32
    summary_freq: 10000
    tau: 0.005
    use_recurrent: true
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    gamma: 0.99
