behaviors:
  SoccerTwos:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: false
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
environment_parameters:
  ball_touch:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.001
        value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.00175
        value: 0.5
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.00225
        value: 0.1
      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.003
        value: 0.0
#env_settings:
#  num_envs: 2
