behaviors:
  VisualHallway:
    trainer: ppo
    batch_size: 64
    beta: 0.01
    buffer_size: 1024
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 1.0e7
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 1
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: true
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
