behaviors:
  Walker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      # extrinsic:
      #   gamma: 0.995
      #   strength: 1.0
      # extrinsic:
      #   gamma: 0.99
      #   strength: 1.0
      # curiosity:
      #   gamma: 0.99
      #   strength: 0.02
      #   network_settings:
      #     hidden_units: 256
      #   learning_rate: 0.0003
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 30000
# env_settings:
#   num_envs: 3
