behaviors:
  DodgeBall:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant 
    network_settings:
      normalize: False
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 32
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 2000
    summary_freq: 50000
    self_play:
      save_steps: 500000
      team_change: 1000000
      swap_steps: 10000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
env_settings:
  num_envs: 3
