default:
    trainer: offline_bc
    batch_size: 64
    beta: 5.0e-3
    hidden_units: 128
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    batches_per_epoch: 10
    num_epoch: 5
    num_layers: 2
    summary_freq: 1000
    use_recurrent: false
    sequence_length: 32
    demo_path: ./UnitySDK/Assets/Demonstrations/Test_2.demo

HallwayBrain:
    trainer: offline_bc
    max_steps: 5.0e5
    num_epoch: 5
    batch_size: 64
    batches_per_epoch: 5
    num_layers: 2
    hidden_units: 128
    sequence_length: 16
    buffer_size: 512
    use_recurrent: true
    memory_size: 256
    sequence_length: 32
    demo_path: ./UnitySDK/Assets/Demonstrations/Hallway.demo

StudentBrain:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: TeacherBrain
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    sequence_length: 16
    buffer_size: 128

StudentRecurrentBrain:
    trainer: online_bc
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: TeacherBrain
    batch_size: 16
    batches_per_epoch: 5
    num_layers: 4
    hidden_units: 64
    use_recurrent: true
    sequence_length: 32
    buffer_size: 128
