default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    curiosity_enc_size: 128
    demo_path: None
    reward_signals: 
     - 'extrinsic'
    reward_strength: 
     - 1.0
    gammas:
     - 0.99

BananaLearning:
    normalize: false
    beta: 0.0
    batch_size: 256
    buffer_size: 2560
    max_steps: 1.0e5

BouncerLearning:
    normalize: true
    beta: 0.0
    max_steps: 5.0e5
    batch_size: 32
    buffer_size: 512
    num_layers: 2
    hidden_units: 64
    summary_freq: 1000
    demo_path: ./demos/ExpertBouncer.demo

PushBlockLearning:
    max_steps: 5.0e4
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    beta: 0.0
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 64
    num_layers: 2
    demo_path: None

SmallWallJumpLearning: 
    max_steps: 1.0e6
    batch_size: 128
    buffer_size: 2048
    beta: 5.0e-3
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

BigWallJumpLearning: 
    max_steps: 1.0e6
    batch_size: 128
    buffer_size: 2048
    beta: 5.0e-3
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

StrikerLearning:
    max_steps: 5.0e5
    learning_rate: 1e-3
    batch_size: 128
    num_epoch: 3
    buffer_size: 2000
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

GoalieLearning:
    max_steps: 5.0e5
    learning_rate: 1e-3
    batch_size: 320
    num_epoch: 3
    buffer_size: 2000
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 128
    num_layers: 2
    normalize: false

PyramidsLearning:
    summary_freq: 2000
    curiosity_enc_size: 256
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 0.0
    max_steps: 5.0e5
    num_epoch: 3
    sequence_length: 32
    demo_path: ./demos/ExpertPyramid.demo
    reward_signals: 
     - 'extrinsic'
     - 'entropy'
     - 'curiosity'
     - 'gail'
    reward_strength: 
     - 1.0
     - 0.001
     - 0.001
     - 0
    gammas:
     - 0.99
     - 0.7
     - 0.7
     - 0.6

VisualPyramidsLearning:
    curiosity_enc_size: 256
    time_horizon: 128
    batch_size: 64
    buffer_size: 2024
    hidden_units: 256
    num_layers: 1
    beta: 1.0e-2
    max_steps: 5.0e5
    num_epoch: 3

3DBallLearning:
    normalize: true
    demo_path: ./demos/ExpertBall.demo
    batch_size: 64
    buffer_size: 12000
    summary_freq: 1000
    time_horizon: 1000
    lambd: 0.99
    beta: 0.001

3DBallHardLearning:
    normalize: true
    batch_size: 1200
    buffer_size: 12000
    summary_freq: 1000
    time_horizon: 1000
    max_steps: 5.0e5
    beta: 0.001

TennisLearning:
    normalize: true
    max_steps: 2e5

CrawlerStaticLearning:
    normalize: true
    extrinsic_strength: 0.0
    demo_path: ./demos/CrawlerDemo2.demo
    num_epoch: 3
    time_horizon: 1000
    batch_size: 1024
    buffer_size: 20240
    max_steps: 1e6
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512

CrawlerDynamicLearning:
    normalize: true
    beta: 0.0
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    max_steps: 1e5
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512

WalkerLearning:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2048
    buffer_size: 20480
    max_steps: 2e6
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512
    demo_path: ./demos/Walker1episode.demo

ReacherLearning:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    gamma: 0.995
    max_steps: 1e6
    summary_freq: 3000

HallwayLearning:
    use_recurrent: true
    sequence_length: 64
    num_layers: 2
    hidden_units: 128
    memory_size: 256
    beta: 0.0
    num_epoch: 3
    buffer_size: 1024
    batch_size: 128
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

VisualHallwayLearning:
    use_recurrent: true
    sequence_length: 64
    num_layers: 1
    hidden_units: 128
    memory_size: 256
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 1024
    batch_size: 64
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

VisualPushBlockLearning:
    use_recurrent: true
    sequence_length: 32
    num_layers: 1
    hidden_units: 128
    memory_size: 256
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 1024
    batch_size: 64
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

GridWorldLearning:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 256
    beta: 5.0e-3
    gamma: 0.9
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 5
    demo_path: ./demos/GridDemo.demo

BasicLearning:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 20
    beta: 5.0e-3
    gamma: 0.9
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 3
