default:
    batch_size: 256
    beta: 2.5e-3
    buffer_size: 5000
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 1.0e6
    normalize: false
    num_epoch: 5
    num_layers: 2
    time_horizon: 64
    sequence_length: 32
    summary_freq: 1000
    use_recurrent: false

Ball3DBrain:
    summary_freq: 1000
    normalize: true
    batch_size: 1024
    max_steps: 1.0e4

TurretBrain: ExampleBrain
ghost-HunterBrain:
    brain_to_copy : HunterBrain
    is_ghost : true
    new_model_freq : 10000
    max_num_models : 20
ghost-HunteeBrain :
    brain_to_copy : HunteeBrain
    is_ghost : true
    new_model_freq : 10000
    max_num_models : 20
ghost-Ball3DBrain:
    brain_to_copy : Ball3DBrain
    is_ghost : true
    new_model_freq : 10000
    max_num_models : 3

Player:
    # is_imitation : true
    max_steps: 10000
    summary_freq: 1000

