behaviors:
  BatonPass:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 640000
    summary_freq: 200000
    checkpoint_interval: 50000000
env_settings:
  # seed: 1
  num_envs: 1
environment_parameters:
  max_food: 20
  penalty: 2.5
  exit_reward: 0
  time_penalty: 5
  collision_penalty: 0.001
  # area_steps: 30000