behaviors:
  SpawnCollector:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # rnd:
      #   gamma: 0.99
      #   strength: 0.01
      #   network_settings:
      #     hidden_units: 64
      #     num_layers: 3
      #   learning_rate: 0.0001
    keep_checkpoints: 5
    max_steps: 40000000
    time_horizon: 64
    summary_freq: 60000
environment_parameters:
  area_steps: 1000
  agent_steps: 600
  button_steps: 200
env_settings:
  num_envs: 1
  seed: 1
