name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-commit:
    if: ${{ github.server_url == 'https://github.cds.internal.unity3d.com' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GHE_ACCESS_TOKEN }}
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7.x
    - uses: actions/setup-ruby@v1
      env:
        ImageOS: ubuntu20
      with:
        ruby-version: '2.6'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
        include-prerelease: true
    - name: Install manual dependencies
      run: |
        python -m pip install pre-commit
        pre-commit install
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
  markdown-link-check:
    # Only run on GitHub Enterprise
    if: ${{ github.server_url == 'https://github.cds.internal.unity3d.com' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.GHE_ACCESS_TOKEN }}
          submodules: recursive
    - uses: actions/setup-python@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install manual dependencies
      run: |
        sudo npm install -g markdown-link-check
        python -m pip install pre-commit
        pre-commit install
    - name: Run markdown checker
      run: |
        pre-commit run --hook-stage manual markdown-link-check --all-files
  validate-meta-files:
    # Only run on GitHub Enterprise
    if: ${{ github.server_url == 'https://github.cds.internal.unity3d.com' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.GHE_ACCESS_TOKEN }}
          submodules: recursive
    - uses: actions/setup-python@v2
    - run: python utils/validate_meta_files.py
